### ISSUE TITLE
[FEATURE] Rules based on project name

### ISSUE THREAD

**Issue by Libeccio84** [gbevan/color-tabs-byproject#10]
It would be really nice to have rules based on project name, instead of on prj path.
In order to do that I changed `getColorForPath` in `lib\color-tabs-byproject.coffee` as follows
```
getColorForPath = (path) ->
  switch atom.config.get "color-tabs-byproject.colorSelection"
    when 'deterministic'
      projPath = resolveProjPath path
      projName = basename projPath
      switch atom.config.get "color-tabs-byproject.referTo"
        when 'project name'
          if rules && rules.projects && rules.projects[projName] && rules.projects[projName].color
            return rules.projects[projName].color
          else
            return getDeterministicColor(projName)
        when 'project path'
          if rules && rules.projects && rules.projects[projPath] && rules.projects[projPath].color
           return rules.projects[projPath].color
          else
            return getDeterministicColor(projPath)
```
adding the following entry in `lib\main.coffee`
```
    referTo:
      title: "Custom rules based on"
      description: "Set rules based on project name, or project full path"
      type: "string"
      default: "project name"
      enum: ["project name", "project path"]
```
